pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        BUILD_PATH = "${WORKSPACE}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Docker Image') {
            agent any
            steps {
                sh 'printenv'
                echo "${BUILD_PATH}"
                dir("${BUILD_PATH}") {
                    sh "pwd"
                }
                //sh 'docker build -t react-test:v1 -f ./jenkins/Dockerfile --no-cache .'
            }
        }
    }
}
