pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Production') {
            steps {
                withAWS(region:'ap-northeast-1',credentials:'production-s3') {
                    s3Delete(bucket: 'live-resource', path:'public/build/*')
                    s3Upload(bucket: 'live-resource', path:'public/build', workingDir:'build', includePathPattern:'**/*')
                }
            }
        }
    }
}
